Repository AnyBody/ammr, pull requests merged in 2024-09, with the labels that each got.

#988 feat(anymocap): Allow overwriting tStart/tEnd/nStep of MarkerTracking
  Tools/AnyMocap/MarkerTrackingSettings.any
Labels: feature

#991 chore: Updated the AnyBodyCon test version to 8.1.0beta1
  pixi.lock
  pixi.toml
Labels: chore

#994 fix: Bug fix free posture pelvis ground driver
  Application/Examples/FreePosture/Model/ConstantDrivers/TrunkDrivers.any
  CHANGELOG.md
  Docs/Applications/Daily-activities-and-ergonomics/FreePosture.md
Labels: fix

#995 fix: Fixed test duration upload
  .github/workflows/nightly-tests.yml
Labels: fix

#993 fix: Updated the version check in template libdef
  Tools/Templates/Human/libdef.any
Labels: fix

#997 feat: Added TRI(N) and TOTAL_POLYLINE_LENGTH(P) code macros
  Body/AAUHuman/BodyModels/GenericBodyModel/Helper.ClassTemplates.any
  CHANGELOG.md
  Tests/test_helper_templates.any
Labels: feature
