Repository AnyBody/ammr, pull requests merged in 2024-04, with the labels that each got.

#940 fix(bvh-protocol): Update foot markers
  CHANGELOG.md
  Tools/AnyMocap/Protocols/XsensBVH.any
Labels: fix

#942 chore: VSCode extensions recommendation
  .gitignore
  .vscode/extensions.json
Labels: chore

#941 fix(AnyMoCap): Ensure force plate visualization can not have zero height
  Tools/AnyMocap/ForcePlates/ForcePlateAutoDetection.any
Labels: fix

#939 fix(trunk): Fixed penetration warning for the pectoralis
  Body/AAUHuman/Arm/AddOnOutSideBlockForMuscles.any
  CHANGELOG.md
  Tests/Applications/test_ExoConcept_BoxLift.any
Labels: fix

#943 fix(ci): Update the custom-anybodycon github-action to work with pixi
  .github/actions/custom-anybodycon/action.yml
  .github/workflows/test-self-hosted.yml
  .github/workflows/test.yml
Labels: fix

#945 chore(test): Update tests to run with AnyBody 8.0.2rc1
  pixi.lock
  pixi.toml
Labels: chore

#946 ci(test): Reenable the wheelchair test
  Tests/Applications/test_WheelChairRancho.any
Labels: CI/CD

#947 ci(test): Update container version to AnyBody 8.0.2rc1 in nightly-tests.yml
  .github/workflows/nightly-tests.yml
Labels: CI/CD

#948 docs: Update links in README.md to point to beta versions of Body Models and Application examples
  Docs/README.md
Labels: documentation

#957 fix: Make the git-info python hook more robust
  Body/AAUHuman/BodyModels/GenericBodyModel/git_info.py
Labels: fix

#958 fix: catch exception when git is missing
  Body/AAUHuman/BodyModels/GenericBodyModel/git_info.py
Labels: fix
