Repository AnyBody/ammr, pull requests merged in 2024-07, with the labels that each got.

#976 ci(test): Combine MoCap model tests in single run
  Tests/AnyMocap/Test_ADL_Gait.any
  Tests/AnyMocap/Test_ADL_Gait_InversDynamics.any
  Tests/AnyMocap/Test_Plug-in-gait_simple_fullbody.any
  Tests/AnyMocap/Test_Plug-in-gait_simple_fullbody_InverseDynamics.any
Labels: CI/CD

#979 chore: update version numbers for 3.0.4 release
  AMMR.version.any
  CHANGELOG.md
Labels: chore

#980 chore: update dependencies and clean up support code
  Application/MocapExamples/Plug-in-gait_Simple/Output/FullBody_GaitNormal_1-euler-left_leg_tlem.txt
  Application/MocapExamples/Plug-in-gait_Simple/Output/FullBody_GaitNormal_1-euler-right_leg_tlem.txt
  Application/MocapExamples/Plug-in-gait_Simple/Output/FullBody_GaitNormal_1-rotvec-left_arm_shoulder.txt
  Application/MocapExamples/Plug-in-gait_Simple/Output/FullBody_GaitNormal_1-rotvec-right_arm_shoulder.txt
  Application/MocapExamples/Plug-in-gait_Simple/Output/FullBody_GaitNormal_1-rotvec-trunk-full.txt
  Application/MocapExamples/Plug-in-gait_Simple/Output/FullBody_GaitNormal_1.anyset
  Application/MocapExamples/Plug-in-gait_Simple/Output/GRF_FullBody_GaitNormal_1-euler-left_leg_tlem.txt
  Application/MocapExamples/Plug-in-gait_Simple/Output/GRF_FullBody_GaitNormal_1-euler-right_leg_tlem.txt
  Application/MocapExamples/Plug-in-gait_Simple/Output/GRF_FullBody_GaitNormal_1-rotvec-left_arm_shoulder.txt
  Application/MocapExamples/Plug-in-gait_Simple/Output/GRF_FullBody_GaitNormal_1-rotvec-right_arm_shoulder.txt
  Application/MocapExamples/Plug-in-gait_Simple/Output/GRF_FullBody_GaitNormal_1-rotvec-trunk-full.txt
  Application/MocapExamples/Plug-in-gait_Simple/Output/GRF_FullBody_GaitNormal_1.anyset
  Tests/recreate_mocap_intermediate_files.py
  pixi.lock
Labels: chore

#981 feat: Implemented HumanGround residuals with rotvector/AngVel=On
  CHANGELOG.md
  Tests/AnyMocap/Test_Plug-in-gait_simple_fullbody_ParamID.any
  Tools/AnyMocap/HumanGroundResiduals.any
  Tools/AnyMocap/KinematicStudyForParameterIdentification.any
  Tools/GRFPrediction/WeakResiduals.any
Labels: feature

#982 fix: Mocap marker arrows Visible switch fix
  CHANGELOG.md
  Docs/body/leg_tlem2_model.md
  Tools/AnyMocap/DrawVector.any
  Tools/AnyMocap/ModelViews.any
Labels: fix

#984 feat: Class template seg com node
  CHANGELOG.md
  Tools/ModelUtilities/SegmentCoM/CreateCoMRefNode.any
Labels: feature

#983 test(ams): Update AMS used in test to 8.0.5rc1
  .github/workflows/nightly-tests.yml
  pixi.lock
  pixi.toml
Labels: test
