Repository AnyBody/ammr, pull requests merged in 2024-12, with the labels that each got.

#1010 test: Adjuested tolerance for symmetry test
  Tests/Symmetry/test_LegDynamicSymmetryCheck.Main.any
Labels: test

#1009 fix: Only call python if it is available
  Body/AAUHuman/BodyModels/GenericBodyModel/BodyModel.defaults.preprocess.any
  Body/AAUHuman/BodyModels/GenericBodyModel/ammr-beta.any
  Body/AAUHuman/BodyModels/GenericBodyModel/git_info.py
  Body/AAUHuman/HumanModel.defs.any
  CHANGELOG.md
Labels: fix

#1011 fix: remove test link from documentation index page
  Docs/index.md
Labels: fix

#1013 fix: remove designvar for muscle activity output in EvaluateMaxLoad class template
  Tests/Applications/test_EvalMaxLoad_loadonly.any
  Tools/ModelUtilities/Validation/EvaluateMaxExternalLoad.any
Labels: fix

#1012 feat: Only load plugins if builtin python is available.
  Body/AAUHuman/BodyModels/GenericBodyModel/BM_Plugin.any
  Body/AAUHuman/BodyModels/GenericBodyModel/BodyModel.defaults.preprocess.any
  Body/AAUHuman/HumanModel.defs.any
  Tools/Plugins/ANSUR_Plugin.any
  pixi.lock
  pixi.toml
Labels: feature
