Repository AnyBody/ammr, pull requests merged in 2025-03, with the labels that each got.

#1028 chore(deps): update anybodycon to version 8.1.0beta3
  pixi.lock
  pixi.toml
Labels: chore

#1027 chore: Bump version to 3.1.0 Beta and update changelog
  AMMR.version.any
  CHANGELOG.md
Labels: chore

#1026 feat: Disable upper bounds for evaluate joint strength studies.
  Body/AAUHuman/Arm/EvaluateJointStrengthStudy.any
  Body/AAUHuman/Leg/EvaluateJointStrengthStudy.any
  Body/AAUHuman/LegTLEM1/EvaluateJointStrengthStudy.any
  Body/AAUHuman/LegTLEM2.1/EvaluateJointStrengthStudy.any
  Body/AAUHuman/Trunk/EvaluateJointStrengthStudy.any
  Tests/Applications/test_EvaluateJointStrength.any
Labels: feature

#1030 chore: test with AMS 8.1 beta 4
  pixi.lock
  pixi.toml
Labels: chore

#1031 fix: Update the positions of the femoral epicondyle nodes with relative to shank in the neutral position.
  Body/AAUHuman/LegTLEM/TLEM2.2/ModelParameters.any
  CHANGELOG.md
Labels: fix

#1033 chore: Release prep for AMMR 3.1
  AMMR.version.any
  CHANGELOG.md
  Docs/conf.py
Labels: chore

#1034 fix: Calibration study muscle inclusion
  Body/AAUHuman/Arm/Calibration/ElbowCal.any
  Body/AAUHuman/Arm/Calibration/WristCal.any
  Body/AAUHuman/Leg/Mus.any
  Tests/test_calibration_lowerbody.any
  Tests/test_calibration_upperbody.any
Labels: fix

#1035 fix: Enhance git_info function to return detailed error messages when failing
  Body/AAUHuman/BodyModels/GenericBodyModel/ammr-beta.any
  Body/AAUHuman/BodyModels/GenericBodyModel/git_info.py
Labels: fix

#1036 feat: Update BM_Plugin path to version 1.1.3 and add associated files
  Body/AAUHuman/BodyModels/GenericBodyModel/BM_Plugin.any
  Tools/Plugins/BM_Plugin-1.1.2-py3.11.ico
  Tools/Plugins/BM_Plugin-1.1.3-py3.11.ico
Labels: feature
