Repository AnyBody/ammr, pull requests merged in 2025-09, with the labels that each got.

#1077 test: Update tests to use 8.1.4beta3
  .github/workflows/nightly-tests.yml
  .github/workflows/test-self-hosted.yml
  .github/workflows/test.yml
  pixi.lock
  pixi.toml
Labels: test

#1078 fix(joint strenth eval): Improve robustness of joint strength eval models
  Body/AAUHuman/Arm/EvaluateJointStrengthStudy.any
  Body/AAUHuman/LegTLEM2.1/EvaluateJointStrengthStudy.any
  Body/AAUHuman/Trunk/EvaluateJointStrengthStudy.any
  CHANGELOG.md
Labels: fix

#1081 feat: More robust check for if Python is available
  Body/AAUHuman/HumanModel.defs.any
Labels: feature

#1083 docs: fix a few anylink issues
  Docs/Applications/Daily-activities-and-ergonomics/StandingLift.md
  Docs/Applications/Daily-activities-and-ergonomics/gallery.txt
  Docs/Applications/Mocap/gallery.txt
  Docs/Applications/Orthopedics_and_rehab/gallery.txt
  Docs/Applications/Other/gallery.txt
  Docs/Applications/Sports/gallery.txt
  Docs/Applications/Validation/gallery.txt
  Docs/Applications/gallery.txt.jinja2
  Docs/exts/anylink.py
Labels: documentation

#1089 fix: Removed SmallStepAssumptionOnOff set to On in InitialCondition analysis
  Tools/AnyMocap/KinematicStudyForParameterIdentificationSettings.any
Labels: fix
